### ISSUE TITLE
Penetration V sometimes sets weapon damage to 0

### ISSUE THREAD

**Issue by Kexerval** [mujmajnkraft/BetterSurvival#10]
Wielding an Ice and Fire 1.8.2 Dragonsteel Saber with Lifesteal I, Ash Destroyer II, Penetration V and Sweeping Edge III causes it to deal 0 damage to mobs.

**Comment by Shivaxi** [comment]
Confirmed, even hitting mobs with armor, 0 damage.  What's weird is penetration V was working for a little bit, but only dealing 2 damage per hit on an iron sword, then after a minute stopped dealing any damage at all.

**Comment by Block-Vader** [comment]
I don't know what might cause this, but I changed how penetration works in 1.3.6. Is it still happening?

**Comment by Kexerval** [comment]
I'll let you know when I update my modpack, which will be in the next few days. @Block-Vader

**Comment by Shivaxi** [comment]
This is fixed in 1.3.6 now =)  just did some extensive testing, thank you!  can close this issue
