### ISSUE TITLE
Weightless on Big shields

### ISSUE THREAD

**Issue by Muddball** [mujmajnkraft/BetterSurvival#12]
Weightless does not seem to be working at all when big shields are held in the 'block' position? 

Suggestion: It would be groovy if the shield enchantments would work on all shields

**Comment by Block-Vader** [comment]
The way shileds apply attributes to the player is currently broken, I will fix it in the next version. Unfortunately, my shileds work differently than shields from vanilla/most other mods, so the enchantments are not compatible.

**Comment by Block-Vader** [comment]
Fixed in 1.3.6.

**Comment by Muddball** [comment]
Nice.
Rats.
Thankyou
