### ISSUE TITLE
Range enchantment broken, arrows constantly build speed, crashes

### ISSUE THREAD

**Issue by Charles445** [mujmajnkraft/BetterSurvival#14]
An arrow shot with range will build speed indefinitely, even when it's not moving.

This can lead to a chain reaction where an arrow that got shot into an unloaded chunk will move way too far when the chunk gets loaded.
If it moves far enough, (i.e. way the heck out of bounds) the server will hang.

Here's a video demonstration where I crash my singleplayer session.
You can see the arrow position and velocity in the chat box.
https://www.youtube.com/watch?v=insESq5XSik

**Comment by Shivaxi** [comment]
bump, is there any way we could get a fix for this in time for RLCraft v2.8 release?

**Comment by Block-Vader** [comment]
I don't know how to fix the bug and I also don't really like how the enchantment works now. I will rework or just remove the enchantment in next major update. For now you should turn it off in the config.

**Comment by Block-Vader** [comment]
Fixed in 1.4.0
