### ISSUE TITLE
this pops up in the log, then freezes all and crashes

### ISSUE THREAD

**Issue by German998** [mujmajnkraft/BetterSurvival#15]
[02:19:19] [Server thread/INFO] [STDOUT]: [com.mujmajnkraft.bettersurvival.potions.PotionWarp:func_76394_a:43]: Performing effect

**Comment by Kexerval** [comment]
@German998 Can you send your crash logs? We really can't pinpoint the issue from this line alone.

**Comment by German998** [comment]
oh yes sorry. it starts at line 8856 (Notepad++) 
*there are others [STDOUT] in the log, but they don't cause this issue.
also it doesnt generates a crash log. this appears in the game log (launcher-console log) 
also im checking DoomlikeDungeons too, cause its dung gen may cause this issue too (cause its an outdated), anws i'll check it removing the mod cause im not sure.
[latest.log](https://github.com/mujmajnkraft/BetterSurvival/files/3800825/latest.log)

**Comment by Block-Vader** [comment]
Seems like the game just keeps trying to teleport you. What happened before the game froze? Did it happen in singleplayer or multiplayer? When I tested the effect everything seemed fine. Does it keep happening when you restart the game?

**Comment by German998** [comment]
Singleplayer Local, it happens when i kill mobs very fast (just hostiles ones) (this time it happened killing wither skeletons) , and well it use to happen randomly without me interacting with anything like if im building something all the world just becomes silent and then freezes. its very strange tbh.

**Comment by Block-Vader** [comment]
Did you do anything with potion of warp? This is currently the only source of Warp effect.

**Comment by German998** [comment]
no, hwvr i've been looking around for entityes w potion effects causing errors and 
changed the line 59  in forge.cfg  to remove erroring entityes and for now it seems to be working just fine. anw if it happens again i'll be updating this thread and posting the log and so . thnx

**Comment by Block-Vader** [comment]
I am unable to reproduce this issue and have no idea what could possibly cause it.
