### ISSUE TITLE
Game crash on initialization (1.12.2)

### ISSUE THREAD

**Issue by SkylordManga** [mujmajnkraft/BetterSurvival#29]
Working on updating my modpack and I got this error after updating Better Survival. if there's  a way to fix this by editing configs that would be great.

[crash-2023-02-04_20.33.11-client.txt](https://github.com/mujmajnkraft/BetterSurvival/files/10610104/crash-2023-02-04_20.33.11-client.txt)

**Comment by Block-Vader** [comment]
It seems you are using a version of Ice and Fire my mod is incompatible with. Unfortunately, there is not an option to switch off IaF integration in config right now, but I may add it in the next patch. For now, you can try using another version of IaF.

**Comment by Block-Vader** [comment]
The most rencent version should no longer crash. I might implement a proper support for the more recent IaF version in the future.
