### ISSUE TITLE
Spear animation ignores "jacket" skin component

### ISSUE THREAD

**Issue by Sninctbur** [mujmajnkraft/BetterSurvival#4]
When preparing to throw a spear, the animation will leave the top layer of the skin alone while the right arm is raised.
![2018-02-18_22 25 00](https://user-images.githubusercontent.com/29333347/36362476-d1d2d528-14fa-11e8-8a5b-b577e3d2579b.png)

**Comment by mujmajnkraft** [comment]
Unfortunately, I don't know if I can solve this issue. The way I use to change position of player's arm is very clunky and I haven't found any better way to do it.

**Comment by Sninctbur** [comment]
[Quark](https://minecraft.curseforge.com/projects/quark?gameCategorySlug=mc-mods&projectID=243121) found a way to do it with its emote system. It might be because of AutoRegLib, however.

**Comment by Block-Vader** [comment]
Quark is actually a coremod and therefore it can add features, which are impossible otherwise. I want to avoid coremodding because it can cause a lot of problems when not done properly and  I am not that good at Java. And with no other way to fix it, I decided to remove the arm rising entirely. :(
