### ISSUE TITLE
Jump height not stacking with other mods features correctly

### ISSUE THREAD

**Issue by Maniacer2** [mujmajnkraft/BetterSurvival#8]
Hi, I'm a RLCraft modpack player reporting a bug.

From Better Survival mod, there's an enchant "High jump" which increases jump height.
From BountifulBaubles mod, there's a balloon which increases jump height.
From Quality Tools mod, there's a quality for bauble items and for leggings which increases jump height by 0,5 block per quality.

I've just finished doing some testing, main result is: when jump height is increased by 1 full block from item qualities(Quality Tools mod), Balloon and High Jump enchant completly stops working.
With Balloon only equiped(without jump boost quality), I can jump 3 blocks at once.
With High Jump II enchant only on boots, I can jump 2,5 blocks at once
With Balloon and High Jump II enchant, I can jump 5 blocks at once. This means High Jump enchant and Balloon stacks.

However, when system detects at least 2 qualities which increase jump height(either on 2 other items or balloon + 1 other item), High Jump and Balloon are disabled.

While playing survival, I made some baubles and was able to jump 4 blocks at once(+3 block jump total), but friend found a balloon from a dungeon. I equiped it and my jump wasn't increased by it(quality disabled it). I equiped balloon only, then it worked. Equiped my baubles with quality and it stopped working.

I simply could play with High Jump and Balloon since they stack while avoiding jump height quality on everything, but there's a quality giving jump height and speed at once, which I really want to use to be jumpy and speedy at once(also 2 potion rings of speed).

Copying & pasting this message to all mods related.

**Comment by Block-Vader** [comment]
The high jump enchantment just adds extra upwards momentum when you jump. I don't see why there should be any compatibility issue.

**Comment by Maniacer2** [comment]
There's for sure something wrong between BetterSurvival/BountifulBaubles and QualityTools. I don't know how mods are created, but maybe qualitytools somehow overrides jump boosts from other mods? You can try this out by yourself, I wrote exacly situations while this bugs out.

**Comment by Kexerval** [comment]
@Maniacer2 It sounds like there's a mod that instead of adding more jump momentum it just sets the jump momentum to their own value, thus conflicting with any other mods that attempt to do the same thing. I don't think this is an issue Block-Vader can fix.

**Comment by Block-Vader** [comment]
There is nothing I can do about it. QualityTools source is not open, so I don't know what exactly it's doing.
